# Generated by Django 4.1 on 2022-08-08 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('messageDelivered', models.BooleanField(default=False)),
                ('messageRead', models.BooleanField(default=False)),
                ('ChatRoomID', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_chat', to='chatrooms.chatroom')),
                ('sender_id', models.ForeignKey(blank='True', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_userID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
