# Generated by Django 4.1 on 2022-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('messageDelivered', models.BooleanField(default=False)),
                ('messageRead', models.BooleanField(default=False)),
            ],
        ),
    ]
