# Generated by Django 4.1 on 2022-08-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ChatRoomID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_chat', to='chatrooms.chatroom'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_id',
            field=models.ForeignKey(blank='True', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_userID', to=settings.AUTH_USER_MODEL),
        ),
    ]
