# Generated by Django 4.1.1 on 2022-09-20 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0007_alter_chatroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='usernames',
            field=models.ManyToManyField(blank='False', related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(blank='False', related_name='chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
