# Generated by Django 4.1.1 on 2022-09-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0009_remove_chatroom_usernames_chatroom_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='usernames',
        ),
    ]
