# Generated by Django 4.1.1 on 2022-09-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0010_remove_chatroom_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='image',
        ),
    ]
